// // import localFont from "next/font/local";
// // import "./globals.css";

// // const geistSans = localFont({
// //   src: "./fonts/GeistVF.woff",
// //   variable: "--font-geist-sans",
// //   weight: "100 900",
// // });
// // const geistMono = localFont({
// //   src: "./fonts/GeistMonoVF.woff",
// //   variable: "--font-geist-mono",
// //   weight: "100 900",
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }


// import "./globals.css";
// import Navbar from "../components/Navbar";
// import Footer from "../components/Footer";

// export const metadata = {
//   title: "TreeVerse",
//   description: "Discover the World of Trees",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="grid grid-rows-[auto_1fr_auto] min-h-screen bg-white text-green-900 font-sans">
//         <Navbar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { Shadows_Into_Light_Two } from "next/font/google";
import { CartProvider } from '../context/CartContext';
const shadowsIntoLightTwo = Shadows_Into_Light_Two({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-shadows-into-light-two",
});

export const metadata = {
  title: "TreeVerse",
  description: "Discover the World of Trees",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={shadowsIntoLightTwo.variable}>
      <body className="grid grid-rows-[auto_1fr_auto] min-h-screen bg-white text-green-900 font-sans">
        <CartProvider>
        <Navbar />
        {children}
        
        <Footer />
        </CartProvider>
      </body>
    </html>
  );
}